### ISSUE TITLE
Release 1.0.3

### ISSUE THREAD

**Issue by equalsraf** [tarruda/libmpack#14]
Cheers, can we get a tagged release that includes the latest changes? In particular the 5.2/5.3 and Makefile fixes.

**Comment by tarruda** [comment]
Release tagged.

I'm working on a cython binding to validate that this library already meets all necessary requirements for being used as a base for language bindings, but didn't get the time to finish it yet, so I will tag another release when it's done

**Comment by glensc** [comment]
seems you forgot to push it?

https://github.com/tarruda/libmpack/releases

last tag still 1.0.2

**Comment by tarruda** [comment]
fixed, also uploaded the lua binding to luarocks
