### ISSUE TITLE
Lua Session does not work when used across coroutine boundaries

### ISSUE THREAD

**Issue by garyburd** [tarruda/libmpack#19]
Environment:

- macOS Sierra 10.12.1
- mpack  1.0.3-0 installed using luarocks
- Lua 5.2.4 installed using brew

Run this program:

```
local mpack = require('mpack')

function cb(...) end

function test(s, p) 
  local data = s:request(cb) .. p("echo") .. p({"foo"})
  local kind, id_or_cb, method_or_error, args_or_result, pos = s:receive(data, 1)
  print(kind, type(id_or_cb), method_or_error, type(args_or_result))
end

local p, s1, s2
local p = mpack.Packer()
local s1 = mpack.Session{unpack = mpack.Unpacker({})}
test(s1, p) -- prints expected output

local co = coroutine.create(function() 
  test(s1, p) -- does not print expected output
  s2 = mpack.Session{unpack = mpack.Unpacker({})}
  test(s2, p) -- prints expected output
end)
coroutine.resume(co)

test(s2, p) -- does not print expected output
```

The output is:

    request	number	echo	table
    request	number	1	string
    request	number	echo	table
    request	number	1	string

The expected output is:

    request	number	echo	table
    request	number	echo	table
    request	number	echo	table
    request	number	echo	table

**Comment by lourkeur** [comment]
Can confirm on:
- Arch Linux
- mpack 1.0.3-0 installed using luarocks
- lua 5.3.3, luarocks 5.2.1, installed via pacman

I tried my hand at a dead-simple fix in #21, maybe that's all there is to it.
