### ISSUE TITLE
Build failures on OSX

### ISSUE THREAD

**Issue by telemachus** [tarruda/libmpack#2]
I'm unable to install mpack on OSX (details below), and it seems to be leading to a problem installing neovim (related to https://github.com/neovim/neovim/issues/4573, I think).

Here's the output of the build failure:

    $ luarocks install mpack
    lmpack.c:185:11: warning: implicit declaration of function 'lua_objlen' is invalid in
          C99 [-Wimplicit-function-declaration]
        len = lua_objlen(L, -1);
              ^
    lmpack.c:1056:14: error: unknown type name 'luaL_reg'; did you mean 'luaL_Reg'?
    static const luaL_reg unpacker_methods[] = {
                 ^~~~~~~~
                 luaL_Reg
    /usr/local/include/lauxlib.h:26:3: note: 'luaL_Reg' declared here
    } luaL_Reg;
      ^
    lmpack.c:1062:14: error: unknown type name 'luaL_reg'; did you mean 'luaL_Reg'?
    static const luaL_reg packer_methods[] = {
                 ^~~~~~~~
                 luaL_Reg
    /usr/local/include/lauxlib.h:26:3: note: 'luaL_Reg' declared here
    } luaL_Reg;
      ^
    lmpack.c:1068:14: error: unknown type name 'luaL_reg'; did you mean 'luaL_Reg'?
    static const luaL_reg session_methods[] = {
                 ^~~~~~~~
                 luaL_Reg
    /usr/local/include/lauxlib.h:26:3: note: 'luaL_Reg' declared here
    } luaL_Reg;
      ^
    lmpack.c:1077:14: error: unknown type name 'luaL_reg'; did you mean 'luaL_Reg'?
    static const luaL_reg mpack_functions[] = {
                 ^~~~~~~~
                 luaL_Reg
    /usr/local/include/lauxlib.h:26:3: note: 'luaL_Reg' declared here
    } luaL_Reg;
      ^
    lmpack.c:1092:3: warning: implicit declaration of function 'luaL_register' is invalid
          in C99 [-Wimplicit-function-declaration]
      luaL_register(L, NULL, unpacker_methods);
      ^
    2 warnings and 4 errors generated.
    
    Error: Build error: Failed compiling object lmpack.o

OSX: 10.10.5
lua: Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
luarocks: 2.3.0

**Comment by justinmk** [comment]
[lua 5.1 header](http://www.lua.org/source/5.1/lauxlib.h.html) defines:

    #define luaL_reg        luaL_Reg

Looks like lua 5.2 removed that. I think we require luajit or lua 5.1.

**Comment by tarruda** [comment]
Should have been closed by https://github.com/tarruda/libmpack/pull/5
