### ISSUE TITLE
Unpacking 0xc1 enters infinite loop

### ISSUE THREAD

**Issue by lourkeur** [tarruda/libmpack#29]
when presented with `b"\xc1"`, the unpacker freezes the entire python process, even defeating Control+C, requiring for the process to be killed manually from another terminal.

There's already a C testcase for the unused code, so I assume the current issue has to do with the python binding.  As stated in #28, I know this is pre-alpha and I'm sorry if I'm wasting time.

Confirmed on 2.7.13 an 3.6.0, test case @ [lourkeur:issue29](https://github.com/lourkeur/libmpack/commit/aa080009686c15ccdc0ca429e4bcca0f03bcdba4)

**Comment by tarruda** [comment]
This is actually a bug in object.c .The reason it wasn't caught in the C tests is because the test was only checking core.c(the token reading part).

I've pushed a fix to #31, thanks for reporting.
