### ISSUE TITLE
Provide a shared library with a proper SONAME

### ISSUE THREAD

**Issue by jamessan** [tarruda/libmpack#4]
I see that Neovim v0.1.4 now has a hard dependency on libmpack (even though it seems to only be used during testing).  Could this start building a shared library with some ABI guarantees?

I'd like to get this packaged for Debian so that I can keep up to date with Neovim's packaging, but I'd prefer to have a shared library to work with.

**Comment by equalsraf** [comment]
@jamessan AFAIK Neovim depends on mpack for more than the tests ([here](https://github.com/neovim/neovim/blob/982198143d3a6f5e9e4880b37206db6fbcb05c7c/scripts/msgpack-gen.lua#L2)). But it does not link against this as is, it uses the resulting lua module within the Neovim lua scripts, here is a recipe to  build the lua module ([PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/lua-mpack))

**Comment by hasufell** [comment]
I'm pretty sure this package is currently the reason a lot of distros don't package the latest neovim. The Makefile does not even have install rules.

**Comment by hasufell** [comment]
https://github.com/tarruda/libmpack/pull/7 this at least adds a compile and install target for system lua, but since I don't know how upstream handles ABI, I won't add a random ABI version scheme
